name: "Release new package version"

on:
  release:
    types:  [ published ]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: actions/setup-node@v2
        with:
          node-version: 12.x
          registry-url: 'https://npm.pkg.github.com'

      - name: Create .netrc
        uses: little-core-labs/netrc-creds@master
        with:
          machine: github.com
          login: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
